## 第八课作业——文本抄袭判定的简单讲解
+ scikit-learn的使用
+ 文本分类的一般流程

# 1.找出判断为新华社但并不是新华社所发的文章
+ 导入数据
+ 文本预处理
+ 文本表征
+ 划分训练集和测试集
+ 训练分类器
+ 验证性能
+ 参数调整
+ 保存和再次使用

In [1]:
import pandas as pd

In [2]:
content = pd.read_csv('D:/Code/Pycharm/Data_source/sqlResult_1558435.csv',encoding='gb18030')

In [3]:
content.head()

id      author                  source  \
0  89617         NaN  快科技@http://www.kkj.cn/   
1  89616         NaN  快科技@http://www.kkj.cn/   
2  89615         NaN  快科技@http://www.kkj.cn/   
3  89614         NaN                     新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  
0     http://www.cnbeta.com/articles/tech/623597.htm  
1     http://www.cnbeta.com/articles/tech/623599.htm  
2     http://www.cnbeta.com/articles/tech/623601.htm  
3  http://world.huanqiu.com/hot/2017-06/10866126....  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...

In [4]:
content[content['source']=='新华社']

id            author source  \
3      89614               NaN    新华社   
39     89578               NaN    新华社   
95     89522               NaN    新华社   
113    89504               NaN    新华社   
305    89312               NaN    新华社   
312    89305               NaN    新华社   
314    89303               NaN    新华社   
543    89074               刘瑞莹    新华社   
545    89072               NaN    新华社   
651    88966                王点    新华社   
671    88946                王点    新华社   
679    88938                王点    新华社   
715    88902                李芳    新华社   
794    88823               卜晓明    新华社   
810    88807               张启畅    新华社   
816    88801               张雪飞    新华社   
909    88708               NaN    新华社   
931    88686               NaN    新华社   
934    88683                邓茜    新华社   
937    88680               NaN    新华社   
940    88677               NaN    新华社   
943    88674                王强    新华社   
946    88671               王乃水    新华社   
951    88666               NaN    新华社   
954    88663               NaN    新华社   
958    88659               NaN    新华社   
964    88653               NaN    新华社   
966    88651               NaN    新华社   
990    88627               NaN    新华社   
995    88622               NaN    新华社   
...      ...               ...    ...   
89581     30       INACIO ROSA    新华社   
89582     29       INACIO ROSA    新华社   
89583     28       INACIO ROSA    新华社   
89584     27       INACIO ROSA    新华社   
89585     26       INACIO ROSA    新华社   
89586     25       INACIO ROSA    新华社   
89587     24      LOVELY GHOSH    新华社   
89588     23      LOVELY GHOSH    新华社   
89589     22      LOVELY GHOSH    新华社   
89590     21      LOVELY GHOSH    新华社   
89591     20      LOVELY GHOSH    新华社   
89592     19                张旌    新华社   
89593     18               NaN    新华社   
89594     17  LISELOTTE SABROE    新华社   
89595     16  LISELOTTE SABROE    新华社   
89596     15  LISELOTTE SABROE    新华社   
89597     14  LISELOTTE SABROE    新华社   
89598     13  LISELOTTE SABROE    新华社   
89599     12  LISELOTTE SABROE    新华社   
89600     11  LISELOTTE SABROE    新华社   
89601     10  LISELOTTE SABROE    新华社   
89602      9  LISELOTTE SABROE    新华社   
89603      8               郑焕松    新华社   
89604      7               郑焕松    新华社   
89605      6               郑焕松    新华社   
89606      5                邹峥    新华社   
89607      4                王衡    新华社   
89608      3                张旌    新华社   
89609      2               夏文辉    新华社   
89610      1            王子江 张寒    新华社   

                                                 content  \
3        这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
39       这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
95     新华社韩国济州6月18日电综述：亚投行第二届年会三大亮点\r\n新华社记者 耿学鹏 严蕾\r...   
113    新华社北京6月18日电 经军委领导批准，《军营理论热点怎么看·2017》日前印发全军。\r\...   
305    新华社兰州6月19日电（记者张钦）记者19日了解到，刚刚出台的《甘肃省网络扶贫行动的实施方案...   
312    新华社乌鲁木齐6月18日电（记者杜刚、王秉阳）6月18日，新疆天山天池首次举办山地马拉松比赛...   
314    新华社北京6月19日电（记者熊丰）记者从公安部消防局获悉，19日上午6时，由公安部消防局组织...   
543    　　暑期旅游旺季是各大旅游景区开门迎客的好时机。然而，有5家5A级景区却高兴不起来：国家旅游...   
545    　　新华社北京6月20日电　总部设在德国波恩的国际残奥委会在当地时间19日宣布，中国残联主席...   
651    　　新华社南京4月17日电(记者潘晔)江苏拥有不少5A景区。日前，一份来自清华大学的第三方调...   
671    　　5月9日，在美国纽约，人们观看巴西里约热内卢的缩微景观。\r\n　　当日，“格列佛大门”...   
679    　　新华社洛杉矶5月9日电(记者高山)美国洛杉矶旅游局9日宣布，洛杉矶2016年接待游客47...   
715    　　机动车在斑马线前不但不减速反而抢行，这类群众反映强烈的城市交通乱象将在本月得到整治。记者...   
794    　　美国亚马逊公司首席执行官杰夫?贝索斯比全球首富比尔?盖茨差多少钱？答案是５０亿美元。\r...   
810    　　新华社巴西利亚６月１９日电（记者张启畅）巴西央行１９日发布每周经济数据报告预计，今年巴西...   
816    　　新华社巴黎６月１９日电（记者张雪飞）第５２届巴黎－布尔歇国际航空航天展览会（巴黎航展）１...   
909    　　新华社北京6月20日电　总部设在德国波恩的国际残奥委会在当地时间19日宣布，中国残联主席...   
931    　　 新华社快讯：国际油价２０日下跌，７月交货的纽约轻质原油期货价格下跌０．９７美元，收于每...   
934    　　新华社伦敦６月２０日电（记者邓茜）伦敦股市《金融时报》１００种股票平均价格指数２０日报收...   
937    　　新华社快讯：纽约商品交易所黄金期货市场交投最活跃的８月黄金期价２０日比前一交易日下跌３．...   
940    　　新华社快讯：伦敦股市《金融时报》１００种股票平均价格指数２０日报收于７４７２．７１点，比...   
943    　　新华社芝加哥６月２０日电（记者王强）芝加哥期货交易所２０日玉米、小麦和大豆期价涨跌不一。...   
946    　　新华社纽约６月２０日电（记者王乃水）美元对多数主要货币汇率２０日上涨。\r\n　　美国联...   
951    　　新华社快讯：摩根士丹利资本国际公司（

In [5]:
content = content.fillna('')

In [6]:
content[content['source'].str.contains('新华')]

id            author source  \
3      89614                      新华社   
17     89600                      新华网   
25     89592                      新华网   
27     89590                      新华网   
39     89578                      新华社   
51     89566                      新华网   
65     89552                     新华社@   
95     89522                      新华社   
104    89513                      新华网   
113    89504                      新华社   
231    89386                      新华网   
305    89312                      新华社   
312    89305                      新华社   
314    89303                      新华社   
329    89288                      新华网   
330    89287                      新华网   
331    89286                      新华网   
335    89282                      新华网   
365    89252                      新华网   
376    89241                      新华网   
388    89229                      新华网   
445    89172                      新华网   
446    89171                      新华网   
448    89169                      新华网   
511    89106                      新华网   
514    89103                      新华网   
541    89076          王璐 PS039  新华通讯社   
543    89074               刘瑞莹    新华社   
545    89072                      新华社   
552    89065                      新华网   
...      ...               ...    ...   
89581     30       INACIO ROSA    新华社   
89582     29       INACIO ROSA    新华社   
89583     28       INACIO ROSA    新华社   
89584     27       INACIO ROSA    新华社   
89585     26       INACIO ROSA    新华社   
89586     25       INACIO ROSA    新华社   
89587     24      LOVELY GHOSH    新华社   
89588     23      LOVELY GHOSH    新华社   
89589     22      LOVELY GHOSH    新华社   
89590     21      LOVELY GHOSH    新华社   
89591     20      LOVELY GHOSH    新华社   
89592     19                张旌    新华社   
89593     18                      新华社   
89594     17  LISELOTTE SABROE    新华社   
89595     16  LISELOTTE SABROE    新华社   
89596     15  LISELOTTE SABROE    新华社   
89597     14  LISELOTTE SABROE    新华社   
89598     13  LISELOTTE SABROE    新华社   
89599     12  LISELOTTE SABROE    新华社   
89600     11  LISELOTTE SABROE    新华社   
89601     10  LISELOTTE SABROE    新华社   
89602      9  LISELOTTE SABROE    新华社   
89603      8               郑焕松    新华社   
89604      7               郑焕松    新华社   
89605      6               郑焕松    新华社   
89606      5                邹峥    新华社   
89607      4                王衡    新华社   
89608      3                张旌    新华社   
89609      2               夏文辉    新华社   
89610      1            王子江 张寒    新华社   

                                                 content  \
3        这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
17     国歌法草案首次提请最高立法机关审议\r\n点击图片进入下一页\r\n新闻：十二届全国人大常委...   
25     当地时间2017年6月17日，土耳其马尼萨省，在土耳其第1步兵训练大队司令部军营，590名土...   
27     英国与欧盟的“脱欧”谈判于19日正式开始。然而此时，英国首相特雷莎·梅正面临着空前的政治压力...   
39       这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
51     戈壁的大漠黄沙曾掩埋了无数西域古道，而如今一条大漠天路正顽强地与黄沙“搏斗”，在乌兰布和、腾...   
65     从百度、支付宝到App?“高考志愿填报”五花八门\r\n顾女士近来减少了刷朋友圈的频率，一有...   
95     新华社韩国济州6月18日电综述：亚投行第二届年会三大亮点\r\n新华社记者 耿学鹏 严蕾\r...   
104    粤港澳概念板块午后走强，珠海港、恒基达鑫、白云机场等个股的午后纷纷快速拉升。\r\n据悉，首...   
113    新华社北京6月18日电 经军委领导批准，《军营理论热点怎么看·2017》日前印发全军。\r\...   
231    东方卫视明星旅游体验综艺节目《旅途的花样》6月17日（周六）晚播出了第三期节目。本周，“花样...   
305    新华社兰州6月19日电（记者张钦）记者19日了解到，刚刚出台的《甘肃省网络扶贫行动的实施方案...   
312    新华社乌鲁木齐6月18日电（记者杜刚、王秉阳）6月18日，新疆天山天池首次举办山地马拉松比赛...   
314    新华社北京6月19日电（记者熊丰）记者从公安部消防局获悉，19日上午6时，由公安部消防局组织...   
329    新华社北京６月２３日电（记者邢静）幸福是人们对生活最美好的期待，２０１７年哪些城市生活更幸福...   
330    新华社昆明6月23日电（记者王研）近年来，随着云南航空业的迅速发展，机场禁毒形势也日益严峻。...   
331    新华社北京６月２３日电（记者倪元锦）２１日起，京津冀迎来今年以来最强降雨。记者采访气象专家，...   
335    新华社北京６月２３日电（记者 倪元锦）２１日起，京津冀迎来今年以来最强降雨。记者采访气象专家...   
365    新华社哈尔滨6月23日电（记者 许正）记者23日从黑龙江省环保厅获悉，这个省目前建立的自然保...   
376    新华社合肥６月２３日电? 题：安徽不断将跨省流域补偿试点推向深入\r\n新华社记者杨丁淼\r...   
388    新华社重庆６月２３日电? 题：“悟空”为何跌下共享风口？——重庆首家共享单车“退市”观察\r...   
445    新华社贵阳６月２３日电（记者 李黔渝）贵州省政府近日下发通知，对严重影响公共安全的中学、医院...   
446    新华社广州6月23日电 题：激发内生动力 走在脱贫路上——广东探索东西部扶贫协作新路径\r\...   
448    新华社南京6月23日电（记者 朱国亮）2

In [7]:
import numpy as np

In [8]:
content['is_xinhua'] = np.where(content['source'].str.contains('新华'),1,0)

In [9]:
content.head()

id      author                  source  \
0  89617              快科技@http://www.kkj.cn/   
1  89616              快科技@http://www.kkj.cn/   
2  89615              快科技@http://www.kkj.cn/   
3  89614                                 新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  is_xinhua  
0     http://www.cnbeta.com/articles/tech/623597.htm          0  
1     http://www.cnbeta.com/articles/tech/623599.htm          0  
2     http://www.cnbeta.com/articles/tech/623601.htm          0  
3  http://world.huanqiu.com/hot/2017-06/10866126....          1  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...          0

In [10]:
content['is_xinhua'][:10]

0    0
1    0
2    0
3    1
4    0
5    0
6    0
7    0
8    0
9    0
Name: is_xinhua, dtype: int32

In [11]:
import jieba

In [12]:
def cut(string):return ' '.join(jieba.cut(string))

In [13]:
cut('今天天气真好')

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Anan\AppData\Local\Temp\jieba.cache
Loading model cost 0.756 seconds.
Prefix dict has been built succesfully.


'今天天气 真 好'

In [14]:
content['title'] = content['title'].fillna('')

In [15]:
content['title'] = content['title'].apply(cut)

In [16]:
help(content.apply)

Help on method apply in module pandas.core.frame:

apply(func, axis=0, broadcast=False, raw=False, reduce=None, args=(), **kwds) method of pandas.core.frame.DataFrame instance
    Applies function along input axis of DataFrame.
    
    Objects passed to functions are Series objects having index
    either the DataFrame's index (axis=0) or the columns (axis=1).
    Return type depends on whether passed function aggregates, or the
    reduce argument if the DataFrame is empty.
    
    Parameters
    ----------
    func : function
        Function to apply to each column/row
    axis : {0 or 'index', 1 or 'columns'}, default 0
        * 0 or 'index': apply function to each column
        * 1 or 'columns': apply function to each row
    broadcast : boolean, default False
        For aggregation functions, return object of same size with values
        propagated
    raw : boolean, default False
        If False, convert each row or column into a Series. If raw=True the
        passed fun

In [17]:
content.head()

id      author                  source  \
0  89617              快科技@http://www.kkj.cn/   
1  89616              快科技@http://www.kkj.cn/   
2  89615              快科技@http://www.kkj.cn/   
3  89614                                 新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                                          title  \
0                小米 MIUI   9 首批 机型 曝光 ： 共计 15 款   
1         骁龙 835 在 Windows   10 上 的 性能 表现 有望 改善   
2         一加 手机 5 细节 曝光 ： 3300mAh 、 充 半小时 用 1 天   
3  葡 森林 火灾 造成 至少 62 人 死亡   政府 宣布 进入 紧急状态 （ 组图 ）   
4       44 岁 女子 约 网友 被 拒 暴雨 中 裸奔   交警 为 其 披衣 相随   

                                                 url  is_xinhua  
0     http://www.cnbeta.com/articles/tech/623597.htm          0  
1     http://www.cnbeta.com/articles/tech/623599.htm          0  
2     http://www.cnbeta.com/articles/tech/623601.htm          0  
3  http://world.huanqiu.com/hot/2017-06/10866126....          1  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...          0

In [18]:
content['title'][:10]

0                  小米 MIUI   9 首批 机型 曝光 ： 共计 15 款
1           骁龙 835 在 Windows   10 上 的 性能 表现 有望 改善
2           一加 手机 5 细节 曝光 ： 3300mAh 、 充 半小时 用 1 天
3    葡 森林 火灾 造成 至少 62 人 死亡   政府 宣布 进入 紧急状态 （ 组图 ）
4         44 岁 女子 约 网友 被 拒 暴雨 中 裸奔   交警 为 其 披衣 相随
5                             金融股 一枝独秀   配置 价值 犹存
6                    配骁龙 660   全面 屏 鼻祖 夏普 新机 酝酿 中
7                          博友 早评 ： 震荡 有利 消化 套牢 筹码
8              武汉 千余 警察 出动   抓获 808 名 俊男靓女 全是 诈骗犯
9                     纳入 MSCI 指数   A股 长期 配置 价值 提升
Name: title, dtype: object

In [43]:
content = content.sample(n=5000)

In [44]:
xinhuashe_news = content[content['source'].str.contains('新华')]

In [45]:
len(xinhuashe_news)

4404

In [46]:
len(content)

5000

In [47]:
len(xinhuashe_news)/len(content)

0.8808

In [48]:
X_title = content['title'].values

In [49]:
y = content['is_xinhua'].values

In [50]:
X_title[:10]

array(['（ 中国 网 事 ） 关于 机票 “ 超售 ” ， 这些 事儿 你 应该 知道', '[ 3 ] （ 外代 二线 ） 瑞士 降雪',
       '清新 25 所 学校 被 评为 清远市 文明 校园', '（ 国际 ） 中 俄 两军 举行 第十九 轮 战略 磋商',
       '韩国 男子 发明 通 马桶 “ 神器 ”', 'QAQ',
       '（ 国际 ） 普京 说 对 叙 化武 事件 进行 没有 根据 的 指认 令人 无法 接受',
       '[ 11 ] （ 外代 二线 ） 网球 — — 蒙特卡洛 大师赛 ： 纳达尔 夺冠',
       '（ 香港回归 二十周年 ） 导演 许鞍华 ： 我 与 香港 七十年', '英国 “ 脱欧 ” 协议 有望 达成'],
      dtype=object)

In [51]:
y[:10]

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0])

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=30000)
X_title = vectorizer.fit_transform(X_title)

In [53]:
X_title.shape

(5000, 10452)

In [54]:
indices = np.arange(len(y))

In [55]:
indices

array([   0,    1,    2, ..., 4997, 4998, 4999])

In [56]:
np.random.shuffle(indices)

In [57]:
indices

array([3994, 2654, 4765, ...,  668, 2553, 1493])

In [58]:
split_test = 0.25

In [59]:
train_indices = indices[int(len(indices)*split_test):]
test_indices = indices[:int(len(indices)*split_test)]

In [60]:
X_t_train,X_t_test,y_train,y_test = (X_title[train_indices],X_title[test_indices],y[train_indices],y[test_indices])

In [61]:
X_t_train

<3750x10452 sparse matrix of type '<class 'numpy.float64'>'
	with 27475 stored elements in Compressed Sparse Row format>

In [62]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_t_train.toarray(), y_train)

GaussianNB(priors=None)

In [63]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
def get_performance(clf, X_, y_):
    y_hat = clf.predict(X_.toarray())
    print('percision is: {}'.format(precision_score(y_, y_hat)))
    print('recall is: {}'.format(recall_score(y_, y_hat)))
    print('roc_auc is: {}'.format(roc_auc_score(y_, y_hat)))
    print('confusion matrix: \n{}'.format(confusion_matrix(y_, y_hat, labels=[0, 1])))

In [64]:
get_performance(clf,X_t_train,y_train)

percision is: 1.0
recall is: 0.9987948177161796
roc_auc is: 0.9993974088580898
confusion matrix: 
[[ 431    0]
 [   4 3315]]


In [65]:
get_performance(clf,X_t_test,y_test)

percision is: 0.9190647482014388
recall is: 0.9419354838709677
roc_auc is: 0.6982404692082111
confusion matrix: 
[[  75   90]
 [  63 1022]]


In [66]:
from sklearn.tree import DecisionTreeClassifier
clf_tree = DecisionTreeClassifier(class_weight={0:5,1:4},criterion='entropy',max_features=5000)
clf_tree.fit(X_t_train,y_train)

DecisionTreeClassifier(class_weight={0: 5, 1: 4}, criterion='entropy',
            max_depth=None, max_features=5000, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [67]:
get_performance(clf_tree,X_t_train,y_train)

percision is: 1.0
recall is: 1.0
roc_auc is: 1.0
confusion matrix: 
[[ 431    0]
 [   0 3319]]


In [68]:
get_performance(clf_tree,X_t_test,y_test)

percision is: 0.9663137632338787
recall is: 0.9253456221198156
roc_auc is: 0.8566122049993018
confusion matrix: 
[[ 130   35]
 [  81 1004]]


In [69]:
y_hat_test = clf.predict(X_t_test.toarray()[:1000])

In [70]:
y_hat_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [71]:
candidate_indices = []
for index, (y,yhat) in enumerate(zip(y_test,y_hat_test)):
    if y == 0 and yhat == 1:
        candidate_indices.append(test_indices[index])

In [72]:
candidate_indices

[1416,
 3047,
 3337,
 688,
 1494,
 1751,
 1169,
 2533,
 1595,
 13,
 2353,
 852,
 4346,
 3357,
 4019,
 2869,
 2528,
 2008,
 3222,
 1746,
 1242,
 3036,
 2496,
 4818,
 2910,
 2122,
 3874,
 4338,
 945,
 3909,
 4837,
 4588,
 4406,
 1408,
 3275,
 3035,
 2154,
 767,
 4086,
 3684,
 2854,
 832,
 3527,
 4719,
 755,
 745,
 1644,
 2094,
 4109,
 4067,
 1810,
 613,
 334,
 3793,
 1563,
 1600,
 2124,
 3415,
 2422,
 457,
 4900,
 3944,
 4903,
 414]

In [74]:
content.iloc[4903]['content']

'????本报讯（记者郭戈通讯员杜红升李群峰）6月19日，省政府金融办、河南银监局联合中国建设银行河南省分行在郑州举行“支持小微企业万户百亿活动”新闻发布会。活动现场，建行正式发布“小微快贷”系列金融产品，并宣布未来3年将通过这一产品向全省6万家小微企业发放贷款300亿元。\r\n????据建行河南省分行行长石永拴介绍，“小微快贷”是运用互联网思维打造的新型金融产品，可通过分析企业及其负责人的房贷信息、涉税信息、金融资产及结算数据等，批量挖掘潜在客户并预测意向授信额度，完全实现了网络化、自助化操作，短短三四分钟便可完成贷款全流程。\r\n????“这将为我省小微企业发展增添新的动力。”省政府金融办主任孙新雷表示。据悉，建行河南省分行目前已在全省21家小企业经营中心、680家营业网点开通了“小微快贷”服务通道。广大小微企业已能通过网上银行办理此项业务，手机银行、智慧柜员机等渠道即将开通。据统计，“小微快贷”试点上线短短一个月来，已为全省近3000家小微企业提供了贷款支持。③4\r\n'

In [75]:
content.iloc[4903]['source']

'河南日报第06版'

In [76]:
import pickle

In [80]:
with open('clf', 'wb') as picklefile:  
    pickle.dump(clf,picklefile)

In [82]:
with open('clf', 'rb') as training_model:  
    model = pickle.load(training_model)

In [83]:
y_hat_test = model.predict(X_t_test.toarray()[:1000])

In [84]:
y_hat_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,