In [1]:
import pandas as pd

In [2]:
contents = pd.read_csv('sqlResult_1558435.csv', encoding='gb18030', keep_default_na=False)

In [3]:
contents

id            author                    source  \
0      89617                      快科技@http://www.kkj.cn/   
1      89616                      快科技@http://www.kkj.cn/   
2      89615                      快科技@http://www.kkj.cn/   
3      89614                                         新华社   
4      89613        胡淑丽_MN7479                     深圳大件事   
5      89612                张怡                 中国证券报?中证网   
6      89611                    威锋网@http://www.feng.com/   
7      89610            申玉彬 整理                 中国证券报?中证网   
8      89609        李杭_BJS4645                 荆楚网-楚天都市报   
9      89608                吴瞬                 中国证券报?中证网   
10     89607                                       证券时报网   
11     89606                                       证券时报网   
12     89605                                       中国新闻网   
13     89604            申玉彬 整理                 中国证券报?中证网   
14     89603                                        国际在线   
15     89602               费天元                     中国证券网   
16     89601                                    solidot@   
17     89600                                         新华网   
18     89599                张怡                 中国证券报?中证网   
19     89598             周佳 整理                 中国证券报?中证网   
20     89597                                         泡泡网   
21     89596             周佳 整理                 中国证券报?中证网   
22     89595                    威锋网@http://www.feng.com/   
23     89594                张怡                 中国证券报?中证网   
24     89593         屠震林 PS040                      凤凰体育   
25     89592                                         新华网   
26     89591                                        雷锋网@   
27     89590                                         新华网   
28     89589                                        中超球评   
29     89588                                      中国经济周刊   
...      ...               ...                       ...   
89581     30       INACIO ROSA                       新华社   
89582     29       INACIO ROSA                       新华社   
89583     28       INACIO ROSA                       新华社   
89584     27       INACIO ROSA                       新华社   
89585     26       INACIO ROSA                       新华社   
89586     25       INACIO ROSA                       新华社   
89587     24      LOVELY GHOSH                       新华社   
89588     23      LOVELY GHOSH                       新华社   
89589     22      LOVELY GHOSH                       新华社   
89590     21      LOVELY GHOSH                       新华社   
89591     20      LOVELY GHOSH                       新华社   
89592     19                张旌                       新华社   
89593     18                                         新华社   
89594     17  LISELOTTE SABROE                       新华社   
89595     16  LISELOTTE SABROE                       新华社   
89596     15  LISELOTTE SABROE                       新华社   
89597     14  LISELOTTE SABROE                       新华社   
89598     13  LISELOTTE SABROE                       新华社   
89599     12  LISELOTTE SABROE                       新华社   
89600     11  LISELOTTE SABROE                       新华社   
89601     10  LISELOTTE SABROE                       新华社   
89602      9  LISELOTTE SABROE                       新华社   
89603      8               郑焕松                       新华社   
89604      7               郑焕松                       新华社   
89605      6               郑焕松                       新华社   
89606      5                邹峥                       新华社   
89607      4                王衡                       新华社   
89608      3                张旌                       新华社   
89609      2               夏文辉                       新华社   
89610      1            王子江 张寒                       新华社   

                                                 content  \
0      此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1      骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2      此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3        这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张

In [4]:
len(contents)

89611

In [5]:
contents['source'].tolist()[:10]

['快科技@http://www.kkj.cn/',
 '快科技@http://www.kkj.cn/',
 '快科技@http://www.kkj.cn/',
 '新华社',
 '深圳大件事',
 '中国证券报?中证网',
 '威锋网@http://www.feng.com/',
 '中国证券报?中证网',
 '荆楚网-楚天都市报',
 '中国证券报?中证网']

In [6]:
import random
import re
import jieba

In [7]:
# word2vec
from gensim import models
from gensim.models import Word2Vec

In [8]:
def prepare_word2vec(contents):
    content = contents['content'].tolist()
    content = [clean_content(con) for con in content]
    
    content = [list(' '.join(jieba.cut(con)).split()) for con in content]
    
    model = Word2Vec(content, min_count=1, workers=4)
    
    return model

In [9]:
from collections import Counter

In [10]:
def to_chunks(_list):
    chunks = []
    for v in _list:
        for t in v:
            chunks.append(t)
    return chunks

In [11]:
def clean_content(content):
    content = re.findall(re.compile('[\w|\d]+'), str(content))
    return ' '.join(content)

In [12]:
def prepare_word_freq(contents):
    content = contents['content'].tolist()
    content = [clean_content(con) for con in content]
    
    content = [list(' '.join(jieba.cut(con)).split()) for con in content]
    
    content = to_chunks(content)
    counter = Counter(content)
    
    return counter

In [13]:
counter = prepare_word_freq(contents)

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/n5/7370hm8s5bn9xb53mkjc1hvm0000gn/T/jieba.cache
Loading model cost 0.820 seconds.
Prefix dict has been built succesfully.


In [14]:
counter['此外']

4239

In [ ]:
#words_model = prepare_word2vec(contents)
#words_model.wv['此外']

In [ ]:
#words_model.save('vector')

In [15]:
words_model = Word2Vec.load('vector')
words_model.wv['此外']

array([ 0.6892026 ,  0.24955116,  2.710645  ,  0.19019109,  0.8447385 ,
       -1.6293007 , -0.67859125, -0.28126398, -1.6926805 ,  1.2687308 ,
       -0.1211135 , -2.38495   ,  2.0963936 , -1.1443421 , -1.2577758 ,
       -0.35566905,  0.11630295, -1.0618734 ,  0.82347137, -0.85503227,
        0.56830144,  1.2596148 , -2.7552133 , -0.08508926,  0.8720204 ,
        1.3996781 , -0.9355065 , -0.48808885,  0.06612434, -0.682085  ,
        0.9126374 , -0.54166424, -0.8425849 , -0.37669444,  0.3917829 ,
       -1.3252648 ,  0.7422436 ,  0.8125048 , -0.24850973, -0.3176164 ,
        1.1147788 ,  0.4956818 ,  1.2212749 , -0.6800729 , -1.1167403 ,
        3.4320877 ,  0.8151205 , -0.60356796,  1.3811148 , -1.6878145 ,
        1.7579801 , -0.49778685,  2.6283915 ,  0.28947648, -3.1473253 ,
       -0.64759475,  0.3195425 , -1.0301567 ,  0.2734693 , -0.07880709,
       -0.98125225, -2.271183  , -0.25428078,  1.1429284 , -1.2484934 ,
       -1.5568385 , -0.28757682, -0.21792255,  0.52652645, -0.01

In [16]:
import jieba
import numpy as np
from numpy import linalg as la
from scipy.spatial.distance import cosine
from sklearn.manifold import TSNE

In [17]:
class Sen2vec:
    def __init__(self, model, word_freq):
        self.scalar_a = 0.0001

        # load word frequency data
        self.word_freq = word_freq

        self.word_vec = model
        
        self.word_sum = 0
        for k, v in word_freq.items():
            self.word_sum += int(v)

    def get_vec(self, sentences):
        # cut to small sentence
        sentences = clean_content(sentences)
        tokens = ' '.join(jieba.cut(sentences)).split()

        sen_vec = 0
        for token in tokens:
            freq = self.word_freq[token]
            vec = self.word_vec.wv[token]
            # print("word:{} freq: {}".format(token, freq))
            # print("word vec: {}, type {}".format(vec, type(vec)))

            sen_vec += self.scalar_a / (self.scalar_a + freq / self.word_sum) * vec
        
        return sen_vec

    def get_cos(self, v1, v2):
        return cosine(v1, v2)

In [18]:
# not correct
sen2vec = Sen2vec(words_model, counter)
vec = sen2vec.get_vec('此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。\r\nMIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。\r\n当然，关于MIUI 9的确切信息，我们还是等待官方消息。\r\n')
vec.shape
# theta = np.zeros((1, 100))
#theta.transpose()
vec = vec.reshape(1, 100)
vec.shape

(1, 100)

In [20]:
vec = np.vstack([vec, vec])
vec

array([[  2.4258041 , -13.168431  ,   5.1470466 ,   5.9999766 ,
         -3.6846905 , -17.146446  ,   4.7596183 , -15.166834  ,
          1.5680331 ,  10.5526495 ,  -5.604319  , -12.150775  ,
         13.503189  ,  -0.39939338,  16.374552  ,  -9.284864  ,
          0.25417274, -21.768562  ,  -6.168717  ,  -5.6528172 ,
          1.4161694 , -11.52272   ,   3.7688646 ,   0.49712625,
         -2.0609586 ,  14.370364  ,  -5.3939347 ,  -1.1354371 ,
          9.515074  ,   1.8224678 , -16.111227  ,  -4.0608263 ,
          6.038208  ,  19.529123  ,   7.602959  ,  -8.00998   ,
          2.6774483 ,   4.9039183 ,  -3.1009474 ,   5.4808807 ,
        -11.609272  , -14.185547  ,   1.2944283 ,   5.603792  ,
         -1.3506216 ,  18.921457  ,  -8.125275  ,  -3.69531   ,
          6.273465  ,  -2.3318918 ,  11.067572  ,  -2.8401093 ,
         15.60359   ,   5.0066257 ,   0.9907219 , -14.033194  ,
        -22.29754   ,  -1.6956853 ,   0.70642954,  -3.3341508 ,
         -4.844927  ,  12.142582  ,   8.

In [21]:
theta = np.zeros((100, 1))
theta.shape

(100, 1)

In [19]:
def add_theta0(x):
    row = x.shape[0]
    one = np.ones((row, 1))
    return np.hstack([one, x])

In [20]:
def cost(x, y, theta, lamb):
    m = x.shape[0]
    column = x.shape[1]
    cost = 0
 
    # time replace space
    for i in range(m):
        h = 1 /(1 + np.exp(np.dot(x[i,:], theta)))
        cost += y[i,:] * np.log(h) + (1 - y[i,:])* np.log(1 - h)
        
    cost = -1 / m * cost - lamb * np.sum(theta**2)
    return cost

In [21]:
class SetType:
    def __init__(self):
        self.text = None
        self.source = None
        self.index = None
        self.vector = None
        self.y = None

In [22]:
class DataSet:
    def __init__(self, corpus, words_model, words_counter,\
                 train_scale=0.6, test_scale=0.2, valid_scale=0.2):
        self.corpus = corpus
        if (train_scale + test_scale + valid_scale > 1):
            print("Error: sum of train, test, valid is bigger than 1")
            return 
        self.content = None
        self.source = None
        self.content_xinhuashe = []
        self.content_not_xinhuashe = []
        
        self.train_scale = train_scale
        self.test_scale = test_scale
        self.valid_scale = valid_scale
        
        self.train_text = None
        self.train = None
        self.test_text = None
        self.test = None
        self.valid_text = None
        self.valid = None
        self.sen2vec = Sen2vec(words_model, words_counter)
        
        self.prepare_data(self.corpus)
        
        
        
    def clean_content(self, content):
        content = re.findall(re.compile('[\w|\d]+'), str(content))
        return ' '.join(content)
    
    def data_init(self, idx):
        data = SetType()
        data.text = self.content[idx]
        data.index = idx
        data.source = self.source[idx]
        data.vector = self.sen2vec.get_vec(data.text)
        return data
        
    def prepare_data(self, corpus):
    
        content = corpus['content'].tolist()
        self.content = [clean_content(con) for con in content]
        self.source = corpus['source'].tolist()
        
        for i in range(len(self.source)):
            if len(self.content[i]) <= 0:
                continue
            data = SetType()
            data.text = self.content[i]
            data.index = i
            data.source = self.source[i]
            data.vector = self.sen2vec.get_vec(data.text)
            if '新华社' in self.source[i]:
                data.y = 1
                self.content_xinhuashe.append(data)
            else:
                data.y = 0
                self.content_not_xinhuashe.append(data)
                
        print(len(self.content_xinhuashe))
        print(len(self.content_not_xinhuashe))
                
        
    def get_random_sample(self, sample, scale):
        rand = random.sample(range(len(sample)), int(len(sample) * scale))
        
        rand_sample = []
        remain_sample = []
        for num in rand:
            rand_sample.append(sample[num])
        
        remain_num = list(set(list(i for i in range(len(sample)))) - set(rand))
        for num in remain_num:
            remain_sample.append(sample[num])
        
        return rand_sample, remain_sample
    
    def get_set(self):
        
        # get train
        train_xinhuashe, remain_xinhuashe = self.get_random_sample(self.content_xinhuashe, self.train_scale)
        
        train_not_xinhuashe, remain_not_xinhuashe = self.get_random_sample(self.content_not_xinhuashe, self.train_scale)
        
        self.train = train_xinhuashe + train_not_xinhuashe
        
        # get text
        test_scale = self.test_scale / (self.test_scale + self.valid_scale)
        test_xinhuashe, remain_xinhuashe = self.get_random_sample(remain_xinhuashe, test_scale)
        
        
        test_not_xinhuashe, remain_not_xinhuashe = self.get_random_sample(remain_not_xinhuashe, test_scale)
        self.test_text = [[1, tra] for tra in test_xinhuashe] \
            + [[0, tra] for tra in test_not_xinhuashe]
        
        self.test = test_xinhuashe + test_not_xinhuashe
        
        # get valid 
        self.valid = remain_xinhuashe + remain_not_xinhuashe

        return self.train, self.test, self.valid
    
    def get_train_text(self):
        return self.train_text
    
    def get_test_text(self):
        return self.test_text
    
    def get_valid_text(self):
        return self.valid_text
        

In [ ]:
dataset = DataSet(contents,words_model, counter)
train, test, valid = dataset.get_set()

In [27]:
len(train)
#len(test)
#len(valid)

52230

In [28]:
def add_theta0(x):
    row = x.shape[0]
    one = np.ones((row, 1))
    return np.hstack([one, x])

In [29]:
def perapare_x_y(data_set):
    #data_x = [[np.insert(data.vector, 0, 1)] for data in data_set]
    data_x = [[data.vector] for data in data_set]
    data_y = [[data.y] for data in data_set]
    
    m = len(data_set)
    n = len(data_set[0].vector)
    
    data_x = np.array(data_x)
    data_x = data_x.reshape(m, n)
    
    data_y = np.array(data_y)
    return data_x, data_y

In [30]:
train_x, train_y = perapare_x_y(train)
test_x, test_y = perapare_x_y(test)
valid_x, valid_y = perapare_x_y(valid)

In [50]:
train_x[0:100,:].shape
#train_x[-100:,:].shape

sample_train_x = np.vstack([train_x[0:100,:], train_x[-100:,:]])

In [106]:
sample_train_y = np.vstack([train_y[0:100,:], train_y[-100:,:]])
sample_train_y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [108]:
from MulticoreTSNE import MulticoreTSNE as TSNE

In [132]:
tsne_train_x = TSNE(n_components=10,n).fit_transform(train_x)
tsne_test_x = TSNE(n_components=10).fit_transform(test_x)
tsne_valid_x = TSNE(n_components=10).fit_transform(valid_x)
tsne_train_x.shape

KeyboardInterrupt: 

In [110]:
ones = np.ones((52230,1))
tsne_train_x = np.hstack((ones, tsne_train_x))
tsne_train_x[0:10,:]

array([[  1.        ,  41.91153685,   2.13482421],
       [  1.        ,  22.43523476,  21.31301968],
       [  1.        , -23.0451217 ,  17.85733361],
       [  1.        ,  21.19661443,  -1.44102248],
       [  1.        , -17.35769518,  10.98826187],
       [  1.        ,  -5.5920736 ,  -7.64508852],
       [  1.        ,   3.56447817, -30.60367058],
       [  1.        , -29.57553959, -29.37356792],
       [  1.        , -27.41199033,  -7.83960226],
       [  1.        , -32.40280687,   1.20542841]])

In [112]:
train_y[-1]

array([0])

In [113]:
def cost(set_x, set_y, theta, lamb):
    m = len(set_x)
    cost = 0

    # time replace space
    for i in range(m):
        x = set_x[i,:]
        h = 1 /(1 + np.exp(np.dot(x, theta)))
        cost += set_y[i] * np.log(h) + (1 - set_y[i])* np.log(1 - h)
        
    cost = -1 / m * cost - lamb * np.sum(theta**2)
    return cost

In [114]:
theta = np.zeros((3, 1))
theta.shape

(3, 1)

In [77]:
tsne_train_x[0,1]

-3.71610426902771

In [69]:
cost(tsne_train_x, sample_train_y, theta, 0.001)

array([0.69314718])

In [115]:
def hx(x, theta):
    h = 1 /(1 + np.exp(np.dot(x, theta)))
    return h

In [116]:
def sumpart(xx, j, theta, y):
    m = xx.shape[0]
    sump = 0
    for i in range(m):
        sump += hx(xx[i,:] - y[i], theta) * xx[i,j]
    
    return sump

In [117]:
def gradient(set_x, set_y, theta, times, alpha, lamb):
    
    m = len(set_x)
    while times:
        tmp_theta = np.zeros((3, 1))
        sump = sumpart(set_x, 0, theta, set_y)
        tmp_theta[0] = theta[0] - alpha * 1 / m * sump
        
        for j in range(1, 3):
            sump = sumpart(set_x, j, theta, set_y)
            tmp_theta[j] = theta[j] - alpha * (1 / m * sump + lamb / m * theta[j])
        
        theta = tmp_theta
        times -= 1
    
    return theta

In [118]:
train_theta = gradient(tsne_train_x, train_y, theta, 20, 0.1, 0.01)

In [120]:
train_theta

array([[-1.02108914],
       [-5.30842332],
       [12.45926354]])

In [121]:
tsne_test_x.shape

(17411, 2)

In [122]:
ones = np.ones((17411,1))
tsne_test_x = np.hstack((ones, tsne_test_x))
tsne_test_x[0:10,:]

array([[  1.        , -15.77837049,  24.41763521],
       [  1.        ,   0.75680872,  36.72794407],
       [  1.        ,   4.40109069,   4.03941367],
       [  1.        ,   1.33724839, -36.2353623 ],
       [  1.        ,   7.85339268,  -2.48574377],
       [  1.        ,  32.83025426,  -6.12920103],
       [  1.        ,  23.64367649, -12.10903116],
       [  1.        ,  31.83192263, -27.4932416 ],
       [  1.        ,  24.563268  ,  41.66397464],
       [  1.        ,  45.15592708,   0.67666799]])

In [130]:
def get_acc():
    acc = 0
    for i in range(len(test)):
        y_1 = hx(tsne_test_x[i,:], train_theta)
        if y_1 > 0.5:
            y_1 = 1
        else:
            y_1 = 0
        y_0 = test[i].y
        print("{} : {}".format(y_1, y_0))

        if y_1 == y_0:
            acc += 1
    
    return acc / len(test) * 100

In [131]:
get_acc()

0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 

1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 

1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 

1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 

1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 

1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 

0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 

0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
1 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
0 : 1
0 : 1
1 : 1
1 : 1
0 : 1
0 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 1
1 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
1 : 1
0 : 1
0 : 1
1 : 0
1 : 0
1 : 0
0 : 0
0 : 0
1 : 0
0 : 0
1 : 0
0 : 0
0 : 0
1 : 0
1 : 0
1 : 0
0 : 0
1 : 0
0 : 0
0 : 0
0 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
0 : 0
1 : 0
1 : 0
0 : 0
0 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
1 : 0
0 : 0
1 : 0
1 : 0
0 : 0
0 : 0
1 : 0
0 : 0
1 : 0
1 : 0
0 : 0
0 : 0
0 : 0
1 : 0
1 : 0
1 : 0
0 : 0
1 : 0
1 : 0
1 : 0
0 : 0
1 : 0
0 : 0
0 : 0
0 : 0
0 : 0
0 : 

49.256217333869394

In [252]:
from sklearn.linear_model import LogisticRegression

In [271]:
logreg = LogisticRegression(C=1e2, solver='saga', multi_class='multinomial',max_iter=200)

In [264]:
re_train_x = train_x.reshape(52230,101)
re_train_x.shape

(52230, 101)

In [267]:
re_train_y = train_y.reshape(52230,)

In [273]:
logreg.fit(re_train_x, re_train_y)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=100.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=None, solver='saga',
          tol=0.0001, verbose=0, warm_start=False)

In [275]:
logreg.predict(test_x[-1,:])

array([1])